name = "eoc.online"
license = "MIT"
licenselink = "https://github.com/eoconline/eoconline.github.io/blob/main/LICENSE"
description = "eoc.onlineâ„¢ provides free tools for Emergency Operations Centers (EOCs) and local ACS/ARES/CERT/MRC/Neighborhood/Citizen Corps groups. For more information check out https://eoc.online."
homepage = "https://github.com/eoconline"
demosite = "https://eoc.online"
min_version = "0.130.0"
version = "1.0.1"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Vashon Software"
homepage = "https://VashonSoftware.com"

[original]
author = "Vashon Software"
homepage = "https://VashonSoftware.com"
repo = "https://github.com/eoconline"
